
server:
  protocol: http
  address: localhost
  port: 8082

  # Userd for mail and download services, can be empty, careful configuration
  # By default, 'server.address' and 'server.port' is used as the string value.
  # access:
  #  address:
  #  port:


## jwt is one of the important configuration of the application
## jwt config cannot be null or empty
jwtToken:
  secret: secret
  timeout: 1800000
  algorithm: HS512


##your datasouce config
source:
  initial-size: 2
  min-idle: 1
  max-wait: 6000
  max-active: 10
  break-after-acquire-failure: true
  connection-error-retry-attempts: 3


spring:
  mvc:
    async:
      request-timeout: 30s

  ## davinci datasouce config
  datasource:
    url: jdbc:mysql://localhost:3306/davinci?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 2
    min-idle: 1
    max-wait: 60000
    max-active: 10

  ## redis config
  ## please choose either of the two ways
  redis:
    isEnable: true

  ## standalone config
    host: 192.168.1.180
    port: 6379

  ## cluster config
  #  cluster:
  #       nodes:

    password: 123456
    database: 9
    timeout: 18000
    jedis:
      pool:
        max-active: 8
        max-wait: 2
        max-idle: 8
        min-idle: 0

  ## mail is one of the important configuration of the application
  ## mail config cannot be null or empty
  ## some mailboxes need to be set separately password for the SMTP service)
  mail:
    host: smtp.qq.com
    port: 465
    username: ljq@senscrm.com
    password: Red123456
    nickname: l

    properties:
      smtp:
        starttls:
          enable: true
          required: true
        auth: true
      mail:
        smtp:
          ssl:
           enable: false

phantomjs_home: D:/java_dev/phantomjs-2.1.1-windows/bin/phantomjs.exe